import json

class Proxy:
    """
    A class that implements the proxy idea.
    Before an answer is generated the Dialogic act model first annotates the student prompt, predicts the next dialogic act. Then the LLM generates the answer based on the predicted dialogic act.
    At the intialization of the class, the generate methods of both the proxy and LLM models should be passed as arguments along with the path to the config file.
    The only method that should be called through API is the response method. The response method should replace the initial response method for the LLM.
    
    """

    

    def __init__(self, generate_proxy, generate_llm,config_path='PROXY.json'):
        """
        Initializes the Proxy class with the generate methods of the proxy and LLM models, and loads the config file.
        The generation methods should expect a string as input, and return a string as output.
        The config file is a JSON file that contains the system prompts and taxonomies for the different generations.
        :param generate_proxy: Generate method of the proxy model that annotates and predicts the next dialogic act.
        :param generate_llm: Generate method of the LLM that generates the answer based on the predicted dialogic act.
        :param config_path: Path to the config file that contains the system prompts and taxonomies for the different generations.
        """
        self.generate_proxy = generate_proxy
        self.generate_llm = generate_llm

        with open(config_path, 'r') as f:
            config = json.load(f)


        self.ANNOTATION_SYSTEM = config["annotation"]
        self.PREDICTION_SYSTEM = config["prediction"]
        self.GENERATION_SYSTEM = config["generation"]

        self.TEACHER_TAX = config["taxonomy_teacher"]
        self.STUDENT_TAX = config["taxonomy_student"]

    
    def format_history(self,system,history,essay,language):
        """
        Formats the input prompts for the different generations.
        :param system: The system prompt to be used for the particular step (annotation, prediction, generation)
        :param essay: The essay written so far by the student
        :param language: The language of the interaction
        """

        if system == self.ANNOTATION_SYSTEM:
            dialog = "\n".join([item['role']+": "+item['content']+" <act= "+item["act"]+">" for item in history[:-1]])
            return system.format(TAXONOMY=self.STUDENT_TAX, ANNOTATED_DIALOGUE=dialog, ESSAY=essay,NEXT_TURN = history[-1]["content"])
        if system == self.PREDICTION_SYSTEM:
            dialog = "\n".join([item['role']+": "+item['content']+" <act= "+item["act"]+">" for item in history])
            return system.format(TAXONOMY=self.TEACHER_TAX, ANNOTATED_DIALOGUE=dialog, ESSAY=essay)
        if system == self.GENERATION_SYSTEM:
            dialog = "\n".join([item['role']+": "+item['content']+" <act= "+item["act"]+">" for item in history[:-1]])
            return system.format(TAXONOMY=self.TEACHER_TAX, ANNOTATED_DIALOGUE=dialog, ESSAY=essay,NEXT_DIALOGIC_ACT=history[-1]["act"],language = language)

        

    
    def annotate(self, history, prompt,essay,language):
        """
        Annotates the student prompt with a dialogic act. The annotation is generated by the proxy model based on past interactions and added to the history.    
        :param history: history of the interaction between the student and the teacher
        :param prompt: student question
        :param essay: The essay written so far by the student
        :param language: The language of the interaction
        :return: Updated history with the annotated student prompt
        """
        history.append({"role":"Student","content":prompt})
        formatted_prompt = self.format_history(self.ANNOTATION_SYSTEM,history,essay,language)
        annotation = self.generate_proxy(formatted_prompt)
        history[-1]["act"] = annotation
        return history
        
    
    def predict(self,history,essay,language):
        """
        Predicts the next dialogic act of the teacher based on the annotated student prompt and past interactions. The prediction is generated by the proxy model and added to the history.
        :param history: history of the interaction between the student and the teacher, including the annotated student prompt
        :param essay: The essay written so far by the student
        :param language: The language of the interaction
        :return: Updated history with the predicted dialogic act of the teacher
        """
        formatted_prompt = self.format_history(self.PREDICTION_SYSTEM,history,essay,language)
        prediction = self.generate_proxy(formatted_prompt)
        history.append({"role":"Teacher","act":prediction})
        return history


    def generate(self,history,essay,language):
        """
        Generates the teacher's response based on the predicted dialogic act and past interactions. The response is generated by the LLM and added to the history.
        The response implements the targeted peadaogical strategy based on the predicted dialogic act.
        
        :param history: history of the interaction between the student and the teacher, including the annotated student prompt and the predicted dialogic act of the teacher.
        :param essay: The essay written so far by the student
        :param language: The language of the interaction

        :return: Updated history with the generated teacher's response
        """
        formatted_prompt = self.format_history(self.GENERATION_SYSTEM,history,essay,language)
        generation = self.generate_llm(formatted_prompt)
        history[-1]["content"] = generation
        return history


    def response(self,history,prompt,s_essay, topic, language):
        """
        Generates the teacher's response based on the student prompt, past interactions, and the essay written so far by the student. The response is generated by the LLM and added to the history.   
        This function implements the proxy idea by first annotating the student prompt, then predicting the next dialogic act of the teacher, and finally generating the teacher's response based on the predicted dialogic act.
        This is the function that should be called through the API instead of the initial response method of the LLM.
        It return the history with the annotated student question, and the response of the model (also annotated with the dialogic act).

        :param history: history of the interaction
        :param prompt: the new student question
        :param s_essay: student essay written so far
        :param topic: topic of the essay
        :param language: language of the interaction

        :return: Updated history with the annotated student prompt, the predicted dialogic act of the teacher, and the generated teacher's response
        """
        essay = "<topic>\n"+topic+"\n</topic>\n" +"<essay>\n"+s_essay+"\n</essay>\n" 
        self.annotate(history,prompt,essay, language)
        self.predict(history,essay, language)
        return self.generate(history,essay, language)






"""
#################################################
SMALL TESTING and Usage example of the Proxy class. 
#################################################
"""
import os
API_KEY = os.environ.get("API_KEY")
import requests

def response(prompt):
    
    url = 'https://hctlsrvb.edu.sot.tum.de/llm//v1/chat/completions'
    headers = {
    'Authorization': f'Bearer {API_KEY}',
    'Content-Type': 'application/json'
    }
    data = {
    "model": "gpt-oss-120b",
    "messages":[{"role": "user", "content": prompt}],
    "stream": False
    }
    response = requests.post(url, headers=headers, json=data)
    return response.json()["choices"][0]["message"]["content"]

### main
if __name__ == "__main__":
    topic = "Should kids be given homework?"
    essay = ""
    language="English"

    proxy = Proxy(generate_proxy=response, generate_llm=response)
    history = []
    while True:
        prompt = input("Student: ")
        if prompt.lower() == "exit":
            break
        history = proxy.response(history, prompt, essay, topic, language)
        print("############################################################\n")
        print(history)
        print("############################################################\n")
        print("Teacher: ", history[-1]["content"])



